anim = {
    "frames": [
        [   # 0: 1.png
            "                                                      ",
            "   `.............................................     ",
            "   .//::::::::::::::::::::::::::::::::::::::::://`    ",
            "   ./+//------------------------------------:////`    ",
            "   ./+//:::::::::::::::::::::::::::::::::::::+///`    ",
            "   ./+//::::::::::::::::::::::::::::::::::::/+///`    ",
            "   ./+//::::/:::::::::::::::::::::::::::/:::/+///`    ",
            "   ./+//:::://////////////////////////////::/+///`    ",
            "   ./+//:::::////////////////////////////:::/+///`    ",
            "   ./+//:::::////////////////////////////:::/+///`    ",
            "   .////:::::////////////////////////////:::/+///`    ",
            "   .////:::::////////////////////////////:::/+///`    ",
            "   .////:::::///:///////////////////::///:::/+///`    ",
            "   .////:::::////:///////////::/::/:::///:::/+///`    ",
            "   .////:::::///:::://///////:/:///:::///:::/+///`    ",
            "   .////:::::///::::////////:::////:::///:::/+///`    ",
            "   .////:::::///::::://////////:::::::///:::/+///`    ",
            "   .////:::::///:::::::/::::::::::::::///:::/+///`    ",
            "   .////:::::/:/::::::::::::::::::::::///:::/+///`    ",
            "   .////:::::/:::::::::::::::::::::::::/::::/+///`    ",
            "   .////::::://://///////////////://:::/::::/+///`    ",
            "   .////:::::::::::::::::::::::::::::::::::::+///`    ",
            "   .////:::::::::::::::::::::::::::::::::::::+///`    ",
            "   .////:::::/:::::::::::::::::::::::::::::::+///`    ",
            "   .////:::::/:::::::::::::::::::::::////+s/:+///`    ",
            "   .////:::::/::::::::::::::::::::::::::::/::+///`    ",
            "   .////:::::/:::::::::::::::::::::::::::+o/:////`    ",
            "   .////:::::/:::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::////`    ",
            "   .////:::::::::::::::::::::::::::::::::::::///:`    ",
            "   .:///:::::::::::::::::::::::::::::::::::::///:`    ",
            "   .:///:::::::::::::::::::::::::::::::::::::///:`    ",
            "   .:///:::::::::::::::::::::::::::::::::::::///:`    ",
            "   .:///:-:::::::::::::::::::::::::::::::::::///:`    ",
            "   .:///:-:::::::::::::::::::::::::::::::::-:///:`    ",
            "   .:///--:::::::::::::::::::::::::::::::::-:/:::`    ",
            "   .:/:/--::::::::::::::::::::::::::::::::--:/:::`    ",
            "   `----.```````````````````````````````````.---.     ",
            "                                                      "
        ],
        [   # 1: 2.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:---:::------------------------------////`    ",
            "    ://+:`:osssssoo+++///:::--....``        .////`    ",
            "    ://+:./sssssssssssssssssssssssssssoooo: .////`    ",
            "    ://+:./ssssooooooooooooooossssssssssss/ ./+//`    ",
            "    ://+:./ssssssssssssssssssssoooooo+/sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+:sss/ ./+//`    ",
            "    ://+:./ssssssssssssssssssssssssss+:sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+:sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+:sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+:sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+:sss/ .////`    ",
            "    ://+:.+ssssssssssssssssssssssssss+:sss/ .////`    ",
            "    ://+:.+ssssssssssssssssssssssssss+:sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+/sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+/sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssss+/sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssso+/sss/ .////`    ",
            "    ://+:./sssssssssssssssssssssssssso/sss/ .////`    ",
            "    ://+:./sssssssssssssssssssssssssssssss/ .////`    ",
            "    ://+:./ssssoooooooooooooooooooooooosss/ .////`    ",
            "    ://+:./ssssssssssssssssssssssssso+:sss/ .////`    ",
            "    ://+:./ssssssssssssssssssssooo+//::+hds-.////`    ",
            "    ://+:./sssssosssssssssssssssssooo+:oyy/ .////`    ",
            "    ://+:./sssssossssssssssssssssssso+:oyh/ .////`    ",
            "    ://+:./sssssssssooooooooooooooooo+/sss/ .////`    ",
            "    ://+:./sssssssssssssssssssssssssssssss/ .////`    ",
            "    ://+:./ssssssssssssssssssoooooooooosss/ .////`    ",
            "    ://+:./ssssoooooooooooooooooooooo+:sss/ .////`    ",
            "    ://+:./sssssossssssssssssssssssso+:sss/ .////`    ",
            "    :///:./sssssossssssssssssssssssso+:sss/ .////`    ",
            "    :///:./sssssossssssssssssssssssoo+:oss/ .////`    ",
            "    :///:./sssssosssssssssssssssssooo+:oss/ .////`    ",
            "    :///:./sssssossssssssssssssssoooo+:ooo/ .///:`    ",
            "    :///:./sssssossssssssssssoooooooo+:ooo/ .///:`    ",
            "    :///:./ssssoosssssssssooooooooooo+:ooo/ .///:`    ",
            "    :///:./sssooosssooooooooooooooooo+:ooo/ .///:`    ",
            "    :///:./osoooooooooooooooooooooooo+:ooo/ .///:`    ",
            "    :///:./osoooooooooooooooooooooooo+:ooo/ .///:`    ",
            "    :///:./oooooooooooooooooooooooooo+:ooo/ .///:`    ",
            "    :///:`/oooooooooooooooooooooooooo+:ooo/ .///:`    ",
            "    :///:`/ooooooooooooooooooooooooooooooo/ .///:`    ",
            "    :///:`/ooooooooooooooooooooooooooo+++/- .///:`    ",
            "    :///:`/oooooooo++///:::---...``         .///:`    ",
            "    ---:.`...```                            `----     ",
            "                                                      "
        ],
        [   # 2: 3.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--::::------------------------------////`    ",
            "    ://+:`:ossssoo+++//:::--...``           .////`    ",
            "    ://+:./sssssssssssssssssssssssssoo+`    .////`    ",
            "    ://+:./sssoooooooooooooosssssssssss.    ./+//`    ",
            "    ://+:./ssssssssssssssssssoooooo/sss.    ./+//`    ",
            "    ://+:./ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:./ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:./ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssoo:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssso/sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssssssssssss.    .////`    ",
            "    ://+:.+ssssooooooooooooooooooooosss.    .////`    ",
            "    ://+:.+sssssssssssssssssssssso+:sss.    .////`    ",
            "    ://+:.+ssssssssssssssssssoo++/:-+dh+    .////`    ",
            "    ://+:./ssssossssssssssssssssoo+:oyy.    .////`    ",
            "    ://+:./ssssosssssssssssssssssoo:oyy.    .////`    ",
            "    ://+:./ssssssoooooooooooooooooo/sss.    .////`    ",
            "    ://+:./ssssssssssssssssssssssssssss.    .////`    ",
            "    ://+:./sssssssssssssssoooooooooosss.    .////`    ",
            "    ://+:./sssoooooooooooooooooooo+:sss.    .////`    ",
            "    ://+:./ssssosssssssssssssssssoo:sss.    .////`    ",
            "    :///:./ssssosssssssssssssssssoo:sss.    .////`    ",
            "    :///:./ssssossssssssssssssssooo:oss.    .////`    ",
            "    :///:./ssssossssssssssssssssoo+:ooo.    .////`    ",
            "    :///:./ssssosssssssssssssssooo+:ooo.    .///:`    ",
            "    :///:./ssssossssssssssssoooooo+:ooo.    .///:`    ",
            "    :///:./sssoossssssosoooooooooo+:ooo.    .///:`    ",
            "    :///:./sssoossosoooooooooooooo+:ooo.    .///:`    ",
            "    :///:./sssoooooooooooooooooooo+:ooo.    .///:`    ",
            "    :///:./ooooooooooooooooooooooo+:ooo.    .///:`    ",
            "    :///:./ooooooooooooooooooooooo+:ooo.    .///:`    ",
            "    :///:`/ooooooooooooooooooooooo+:ooo.    .///:`    ",
            "    :///:`/oooooooooooooooooooooooooooo.    .///:`    ",
            "    :///:`/oooooooooooooooooooooooo+++/`    .///:`    ",
            "    :///:`/ooooooo++///:::--...``           .///:`    ",
            "    ---:.`...``                             `----     ",
            "                                                      "
        ],
        [   # 3: 4.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--::::------------------------------////`    ",
            "    ://+:`:ossssoo++///::--...``            .////`    ",
            "    ://+:./sssssssssssssssssssssssoo+.      .////`    ",
            "    ://+:./sssoooooooooooosssssssssss.      .////`    ",
            "    ://+:./sssssssssssssssssooooo/sss.      .////`    ",
            "    ://+:./ssssssssssssssssssssso:oss.      ./+//`    ",
            "    ://+:.+ssssssssssssssssssssso:oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso:oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso:oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso:oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso:oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso/oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso/oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso/oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso/oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso/oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso/oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso/oss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssssssss.      .////`    ",
            "    ://+:.+sssoooooooooooooooooooosss.      .////`    ",
            "    ://+:.+ssssssssssssssssssssso:oss.      .////`    ",
            "    ://+:.+sssssssssssssssssoo+//-+hh+      .////`    ",
            "    ://+:.+sssssssssssssssssssooo:oyy.      .////`    ",
            "    ://+:./ssssssssssssssssssssoo:oyy.      .////`    ",
            "    ://+:./ssssssoooooooooooooooo/oss.      .////`    ",
            "    ://+:./ssssssssssssssssssssssssss.      .////`    ",
            "    ://+:./sssssssssssssssoooooooosss.      .////`    ",
            "    ://+:./sssooooooooooooooooooo:oss.      .////`    ",
            "    :///:./ssssosssssssssssssssso:oss.      .////`    ",
            "    :///:./ssssosssssssssssssssso:oss.      .////`    ",
            "    :///:./ssssosssssssssssssssoo:oss.      .////`    ",
            "    :///:./ssssossssssssssssssooo:oos.      .////`    ",
            "    :///:./ssssossssssssssssssooo:ooo.      .///:`    ",
            "    :///:./ssssossssssssssooooooo:ooo.      .///:`    ",
            "    :///:./sssoosssssoososooooooo:ooo.      .///:`    ",
            "    :///:./sssoosoooooooooooooooo:ooo.      .///:`    ",
            "    :///:./ssoooooooooooooooooooo:ooo.      .///:`    ",
            "    :///:./oooooooooooooooooooooo:ooo.      .///:`    ",
            "    :///:./oooooooooooooooooooooo:ooo.      .///:`    ",
            "    :///:`/oooooooooooooooooooooo:ooo.      .///:`    ",
            "    :///:`/oooooooooooooooooooooooooo.      .///:`    ",
            "    :///:`/ooooooooooooooooooooooo++/`      .///:`    ",
            "    :///:`/ooooooo++//::---..``             .///:`    ",
            "    ---:.`...``                             `----     ",
            "                                                      "
        ],
        [   # 4: 5.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--:::-------------------------------////`    ",
            "    ://+:`:osssoo+++//::--...`              .////`    ",
            "    ://+:./ssssssssssssssssssssssoo:        .////`    ",
            "    ://+:./sssooooooooooossssssssss/        .////`    ",
            "    ://+:./sssssssssssssssooooo+/ss/        .////`    ",
            "    ://+:./ssssssssssssssssssss+/ss/        ./+//`    ",
            "    ://+:.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+:.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+:.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+:.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+:.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+/.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+:.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+:.+sssssssssssssssssssso/ss/        .////`    ",
            "    ://+:.+ssssssssssssssssssss+/ss/        .////`    ",
            "    ://+:.+ssssssssssssssssssss+/ss/        .////`    ",
            "    ://+:.+ssssssssssssssssssso+/ss/        .////`    ",
            "    ://+:.+sssssssssssssssssssso+ss/        .////`    ",
            "    ://+:.+ssssssssssssssssssssssss/        .////`    ",
            "    ://+:.+sssoooooooooooooooooooss/        .////`    ",
            "    ://+:.+ssssssssssssssssssso+/ss/        .////`    ",
            "    ://+:.+ssssssssssssssssoo+/::oms.       .////`    ",
            "    ://+:.+ssssssssssssssssssoo+/oy/        .////`    ",
            "    ://+:./ssssssssssssssssssso+/sh/        .////`    ",
            "    ://+:./ssssssoooooooooooooo+/ss/        .////`    ",
            "    ://+:./ssssssssssssssssssssssss/        .////`    ",
            "    ://+:./sssssssssssssoooooooooss/        .////`    ",
            "    ://+:./sssooooooooooooooooo+/ss/        .////`    ",
            "    ://+:./ssssssssssssssssssso+/ss/        .////`    ",
            "    :///:./sssossssssssssssssso+/ss/        .////`    ",
            "    :///:./sssossssssssssssssoo+/ss/        .////`    ",
            "    :///:./sssossssssssssssssoo+/ss/        .////`    ",
            "    :///:./sssosssssssssssosooo+/oo/        .///:`    ",
            "    :///:./sssossssssssssoooooo+/oo/        .///:`    ",
            "    :///:./sssoosssssosoooooooo+/oo/        .///:`    ",
            "    :///:./sssoosssoooooooooooo+/oo/        .///:`    ",
            "    :///:./osoooooooooooooooooo+/oo/        .///:`    ",
            "    :///:./oooooooooooooooooooo+/oo/        .///:`    ",
            "    :///:./oooooooooooooooooooo+/oo/        .///:`    ",
            "    :///:`/oooooooooooooooooooo+/oo/        .///:`    ",
            "    :///:`/oooooooooooooooooooooooo/        .///:`    ",
            "    :///:`/ooooooooooooooooooooo++/-        .///:`    ",
            "    :///:`/oooooo++//:::--..``              .///:`    ",
            "    ---:.`..```                             `----     ",
            "                                                      "
        ],
        [   # 5: 6.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--:::-------------------------------////`    ",
            "    ://+:`:osssoo++//::--..``               .////`    ",
            "    ://+:./ssssssssssssssssssssoo-          .////`    ",
            "    ://+:./sssoooooooooosssssssss:          .////`    ",
            "    ://+:./ssssssssssssssooooo/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso:ss:          ./+//`    ",
            "    ://+:.+sssssssssssssssssso:ss:          ./+//`    ",
            "    ://+:.+sssssssssssssssssso:ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso:ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+sssssssssssssssssso/ss:          .////`    ",
            "    ://+:.+ssssssssssssssssssssss:          .////`    ",
            "    ://+:.+sssoooooooooooooooooss:          .////`    ",
            "    ://+:.+sssssssssssssssssso:ss:          .////`    ",
            "    ://+:.+ssssssssssssssso+//:oms`         .////`    ",
            "    ://+:.+ssssssssssssssssooo:oy:          .////`    ",
            "    ://+:.+sssssssssssssssssoo:sh:          .////`    ",
            "    ://+:.+sssssssoooooooooooo/ss:          .////`    ",
            "    ://+:.+ssssssssssssssssssssss:          .////`    ",
            "    ://+:./ssssssssssssooooooooss:          .////`    ",
            "    ://+:./ssooooooooooooooooo:ss:          .////`    ",
            "    ://+:./sssosssssssssssssso:ss:          .////`    ",
            "    :///:./sssosssssssssssssso:ss:          .////`    ",
            "    :///:./sssosssssssssssssoo:ss:          .////`    ",
            "    :///:./sssosssssssssssssoo:ss:          .////`    ",
            "    :///:./sssosssssssssssoooo:oo:          .///:`    ",
            "    :///:./sssosssssssssoooooo:oo:          .///:`    ",
            "    :///:./sssosssssosoooooooo:oo:          .///:`    ",
            "    :///:./ssoosssssoooooooooo:oo:          .///:`    ",
            "    :///:./ssoosoooooooooooooo:oo:          .///:`    ",
            "    :///:./ooooooooooooooooooo:oo-          .///:`    ",
            "    :///:./ooooooooooooooooooo:oo-          .///:`    ",
            "    :///:`/ooooooooooooooooooo:oo-          .///:`    ",
            "    :///:`/oooooooooooooooooooooo-          .///:`    ",
            "    :///:`/ooooooooooooooooooo++/-          .///:`    ",
            "    :///:`/ooooo++///::-..``                .///:`    ",
            "    ---:.`..``                              `----     ",
            "                                                      "
        ],
        [   # 6: 7.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--:::-------------------------------////`    ",
            "    ://+:`/sssoo++//::-..``                 .////`    ",
            "    ://+:./sssssssssssssssssoo+             .////`    ",
            "    ://+:./ssooooooooosssssssss             .////`    ",
            "    ://+:.+ssssssssssssoooo++ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             ./+//`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+sssssssssssssssso+ss             .////`    ",
            "    ://+:.+sssssssssssssssso+ss             .////`    ",
            "    ://+:.+sssssssssssssssso+ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+ssssssssssssssss++ss             .////`    ",
            "    ://+:.+sssssssssssssssso+ss             .////`    ",
            "    ://+:.+ssssssssssssssssssss             .////`    ",
            "    ://+:.+ssooooooooooooooooss             .////`    ",
            "    ://+:.+ssssssssssssssss+/ss             .////`    ",
            "    ://+:.+ssssssssssssso+/:/hh.            .////`    ",
            "    ://+:.+ssssssssssssssso+/ss             .////`    ",
            "    ://+:.+ssssssssssssssso++yy             .////`    ",
            "    ://+:.+ssssssoooooooooo++so             .////`    ",
            "    ://+:.+ssssssssssssssssssso             .////`    ",
            "    ://+:.+sssssssssssoooooooso             .////`    ",
            "    ://+:.+ssoooooooooooooo+/so             .////`    ",
            "    ://+:.+ssssssssssssssss+/so             .////`    ",
            "    :///:./ssssssssssssssss+/so             .////`    ",
            "    :///:./sssossssssssssso+/so             .////`    ",
            "    :///:./sssossssssssssso+/oo             .////`    ",
            "    :///:./sssossssssssssso+/oo             .///:`    ",
            "    :///:./ssoosssssssooooo+/oo             .///:`    ",
            "    :///:./ssoossssoooooooo+/oo             .///:`    ",
            "    :///:./ssoossoooooooooo++oo             .///:`    ",
            "    :///:./sooooooooooooooo+/oo             .///:`    ",
            "    :///:./oooooooooooooooo+/oo             .///:`    ",
            "    :///:./oooooooooooooooo+/oo             .///:`    ",
            "    :///:`/oooooooooooooooo+/oo             .///:`    ",
            "    :///:`/oooooooooooooooooooo             .///:`    ",
            "    :///:`/ooooooooooooooooo++/             .///:`    ",
            "    :///:`/ooooo+//::--.``                  .///:`    ",
            "    ---:.`..``                              `----     ",
            "                                                      "
        ],
        [   # 7: 8.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--::--------------------------------////`    ",
            "    ://+:`/ssso+//:--.`                     .////`    ",
            "    ://+:./sssssssssssssso/                 .////`    ",
            "    ://+:.+ssooooooosssssso                 .////`    ",
            "    ://+:.+ssssssssssooo/so                 ./+//`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssss/so                 .////`    ",
            "    ://+:.+sssssssssssso/so                 .////`    ",
            "    ://+:.+sssssssssssss+so                 .////`    ",
            "    ://+:.+sssssssssssssss+                 .////`    ",
            "    ://+:.+ssoooooooooooos+                 .////`    ",
            "    ://+:.+sssssssssssso/s+                 .////`    ",
            "    ://+:.+sssssssssso+/:sy.                .////`    ",
            "    ://+:.+sssssssssssoo/so                 .////`    ",
            "    ://+:.+sssssssssssso/so                 .////`    ",
            "    ://+:.+sssoooooooooo/s+                 .////`    ",
            "    ://+:.+sssssssssssssss+                 .////`    ",
            "    ://+:.+sssssssssooooos+                 .////`    ",
            "    ://+:.+soooooooooooo/s+                 .////`    ",
            "    ://+:.+sssssssssssso/s+                 .////`    ",
            "    :///:.+sssssssssssso/s+                 .////`    ",
            "    :///:.+ssossssssssso/s+                 .////`    ",
            "    :///:.+ssossssssssoo/o+                 .////`    ",
            "    :///:./ssossssssssoo/o+                 .///:`    ",
            "    :///:./ssossssssoooo/o+                 .///:`    ",
            "    :///:./ssosssooooooo/o+                 .///:`    ",
            "    :///:./soooooooooooo/o+                 .///:`    ",
            "    :///:./soooooooooooo/o+                 .///:`    ",
            "    :///:./ooooooooooooo/o+                 .///:`    ",
            "    :///:./ooooooooooooo/o+                 .///:`    ",
            "    :///:`/ooooooooooooo/o+                 .///:`    ",
            "    :///:`/ooooooooooooooo+                 .///:`    ",
            "    :///:`/oooooooooooooo+:                 .///:`    ",
            "    :///:`/oooo+//:-..`                     .///:`    ",
            "    ---:.`..`                               `----     ",
            "                                                      "
        ],
        [   # 8: 9.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--::--------------------------------////`    ",
            "    ://+:`/sso++/:-.`                       .////`    ",
            "    ://+:./sssssssssssso`                   .////`    ",
            "    ://+:.+soooooossssss`                   ./+//`    ",
            "    ://+:.+ssssssssooo+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssso+s`                   .////`    ",
            "    ://+:.+sssssssssss+s`                   .////`    ",
            "    ://+:.+sssssssssssss`                   .////`    ",
            "    ://+:.+ssoooooooooos`                   .////`    ",
            "    ://+:.+sssssssssso/s`                   .////`    ",
            "    ://+:.+sssssssso+/:h:                   .////`    ",
            "    ://+:.+sssssssssso/y`                   .////`    ",
            "    ://+:.+sssssssssso/y`                   .////`    ",
            "    ://+:.+sssoooooooo+s`                   .////`    ",
            "    ://+:.+sssssssssssss`                   .////`    ",
            "    ://+:.+sssssssooooos`                   .////`    ",
            "    ://+:.+soooooooooo/s`                   .////`    ",
            "    ://+:.+sssssssssso/s`                   .////`    ",
            "    :///:.+sssssssssso/s`                   .////`    ",
            "    :///:.+sosssssssso/s`                   .////`    ",
            "    :///:.+sosssssssso/s`                   .////`    ",
            "    :///:.+sosssssssoo/o`                   .///:`    ",
            "    :///:.+sossssssooo/o`                   .///:`    ",
            "    :///:.+sosssssoooo/o`                   .///:`    ",
            "    :///:./sosoooooooo/o`                   .///:`    ",
            "    :///:./soooooooooo/o`                   .///:`    ",
            "    :///:./ooooooooooo/o`                   .///:`    ",
            "    :///:./ooooooooooo/o`                   .///:`    ",
            "    :///:`/ooooooooooo/o`                   .///:`    ",
            "    :///:`/ooooooooooooo`                   .///:`    ",
            "    :///:`/ooooooooooo++`                   .///:`    ",
            "    :///:`/ooo+/::-.`                       .///:`    ",
            "    .--:.`..`                               `----     ",
            "                                                      "
        ],
        [   # 9: 10.png
            "                                                      ",
            "    .............................................     ",
            "    :/::::::::::::::::::::::::::::::::::::::::://`    ",
            "    :///:--:---------------------------------////`    ",
            "    ://+:`/so+/:.`                          .////`    ",
            "    ://+:./sssssssso                        .////`    ",
            "    ://+:.+soooossss                        .////`    ",
            "    ://+:.+sssssso+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssssos                        .////`    ",
            "    ://+:.+sssssssss                        .////`    ",
            "    ://+:.+sooooooos                        .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+ssssss+:h`                       .////`    ",
            "    ://+:.+sssssss+s                        .////`    ",
            "    ://+:.+sssssss+y                        .////`    ",
            "    ://+:.+soooooo+s                        .////`    ",
            "    ://+:.+sssssssss                        .////`    ",
            "    ://+:.+ssssoooos                        .////`    ",
            "    ://+:.+soooooo+o                        .////`    ",
            "    ://+:.+sssssss+o                        .////`    ",
            "    ://+:.+sssssss+o                        .////`    ",
            "    ://+:.+sssssss+o                        .////`    ",
            "    ://+:.+sssssso+o                        .////`    ",
            "    :///:./sssssso+o                        .////`    ",
            "    :///:./sssssoo+o                        .///:`    ",
            "    :///:./sossooo+o                        .///:`    ",
            "    :///:./soooooo+o                        .///:`    ",
            "    :///:./ooooooo+o                        .///:`    ",
            "    :///:./ooooooo+o                        .///:`    ",
            "    :///:./ooooooo+o                        .///:`    ",
            "    :///:`/ooooooo+o                        .///:`    ",
            "    :///:`/ooooooooo                        .///:`    ",
            "    :///:`/ooooooo+/                        .///:`    ",
            "    :///:`/o+/:-.                           .///:`    ",
            "    .---. ``                                `---.     ",
            "                                                      "
        ]
    ],
    "order": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    "repeat": 1,
    "rate": 12
}

